name: user_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.0 
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.12
  workout_manager_api:
    path: ../workout_manager_api

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0