// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-ulzWopIFjrFj7s-tOQLEWLlvSAxXFw',
    appId: '1:495706644724:web:a815de693ecb7ca11efea1',
    messagingSenderId: '495706644724',
    projectId: 'wod-generator-eb509',
    authDomain: 'wod-generator-eb509.firebaseapp.com',
    storageBucket: 'wod-generator-eb509.appspot.com',
    measurementId: 'G-K9H6MXBVBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiGTXbMs99S4rFjSWtqgNWa8P6Rn-1QE',
    appId: '1:495706644724:android:d1d989aecf5c29a81efea1',
    messagingSenderId: '495706644724',
    projectId: 'wod-generator-eb509',
    storageBucket: 'wod-generator-eb509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_L8Zi4fWCwpNN45pTbPqP1QV4zzqPds',
    appId: '1:495706644724:ios:76923be8af952b891efea1',
    messagingSenderId: '495706644724',
    projectId: 'wod-generator-eb509',
    storageBucket: 'wod-generator-eb509.appspot.com',
    iosClientId: '495706644724-aef7aik019n3c5p238pnk7c49br9snsr.apps.googleusercontent.com',
    iosBundleId: 'com.ortiz.bryan',
  );
}
