# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

FIREBASE_TOKEN = ENV["FIREBASE_TOKEN"]

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Push a new beta build to Firebase"
  lane :firebase do |options|
    setup_ci if ENV['CI']

    id = "1:495706644724:ios:76923be8af952b891efea1"
    latest_release = firebase_app_distribution_get_latest_release(
      app: id
    )

    increment_build_number({ build_number: latest_release[:buildVersion].to_i + 1 })
    # app_store_connect_api_key()

    match(
      type: "adhoc",
      readonly: true,
    )
    build_app(
      workspace: "Runner.xcworkspace", 
      scheme: "Runner", 
      export_method: "ad-hoc",
    )
    firebase_app_distribution(
      app: id,
      groups: "family",
      release_notes: "Lots of amazing new features to test out!",
      firebase_cli_token: FIREBASE_TOKEN
    )
  end
end
