name: workout_manager_api
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  http: ^0.13.4
  equatable: ^2.0.0 
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0