name: distribute-ios-app
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # - run: cd ios 
      - run: cd ios && pwd && ls && fastlane firebase
        # env:
        #   MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}