name: distribute-ios-app
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: fastlane firebase
        # env:
        #   MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}